---
- name: Setup a mac dev system
  hosts: localhost

  pre_tasks:
    - name: Check if Homebrew is installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check
    - name: Install Homebrew if needed
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists

  roles:
    - install_homebrew_packages
