---
# tasks file for install_vscode_extensions

# Ensure extensions are present
- name: Install extensions
  shell: code --install-extension {{ item }}
  with_items: "{{ install_vscode_extensions_list }}"
